// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kufxqcmzaztnnkskgpnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZnhxY216YXp0bm5rc2tncG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NzYyMzIsImV4cCI6MjA1MDU1MjIzMn0.dLbqH34AVwKnFe0tKUJbWRWmOzBNYihwo0jzJyaoHBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);